# from: <https://github.com/tauri-apps/tauri/blob/tauri-v2.2.2/.github/ISSUE_TEMPLATE/bug_report.yml>

name: ðŸž Bug Report
title: '[bug] '
description: Report a bug (not a question)
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        ## First of all

        1. Please search for existing [tauri issues](https://github.com/tauri-apps/tauri/issues) and [pytauri issues](https://github.com/WSH032/pytauri/issues) about this problem first.
        2. Make sure `rustc` and all relevant Tauri/PyTauri packages are up to date.
        3. Make sure it's an **issue** with **PyTauri** and not something else you are using.
            - If it's a Tauri issue, please report it to Tauri's repository.
            - If it's a question, please use `Discussion->Q&A` instead.

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear description of what the bug is. Include screenshots if applicable.
      placeholder: Bug description
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: |
        A link to a reproduction repo or steps to reproduce the behaviour.

        Please provide a minimal reproduction or steps to reproduce, see this guide <https://stackoverflow.com/help/minimal-reproducible-example>.

        Why reproduction is required? see this article <https://antfu.me/posts/why-reproductions-are-required>.
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: tauri-info
    attributes:
      label: Full `tauri info` output
      description: 'Output of `npm run tauri info` or `cargo tauri info`'
      render: text
    validations:
      required: true

  - type: textarea
    id: py-info
    attributes:
      label: Your python info and denpendencies
      value: |
          ### python version

          `3.*` ðŸ‘ˆ edit

          ### denpendencies

          `uv pip freeze` or `pip freeze`

          <details>
          <summary>detail</summary>

          ```text
          # edit here ðŸ‘‡
          annotated-types==0.7.0
          ...
          ```

          </details>
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Stack trace / logs / console output
      render: text

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
